---
- hosts: linux
  tasks:
  - name: upload the file to target server
    copy:
      src: /root/shell.sh
      dest: /home/ansible/shell.sh
      mode: 0755
  - name: modify the script
    lineinfile:
      state: present
      dest: /home/ansible/shell.sh
      regexp: '^HOST='
      line: HOST={{ ansible_hostname }}
  - name: run the script
    shell: /home/ansible/shell.sh
    register: output
  - debug: msg=" output is {{output.stdout}}"
